//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxerWorkoutMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoxerWorkoutMaster()
        {
            this.BoxerWorkoutSchedules = new HashSet<BoxerWorkoutSchedule>();
            this.BoxerWorkoutTemplateMappings = new HashSet<BoxerWorkoutTemplateMapping>();
            this.BoxerWorkoutUserMappings = new HashSet<BoxerWorkoutUserMapping>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string WorkoutDescription { get; set; }
        public Nullable<bool> IsReadyForLocations { get; set; }
        public string WorkoutName { get; set; }
        public string PDFName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> FrontCoverImageId { get; set; }
        public Nullable<int> BackCoverImageId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ImageGallery ImageGallery { get; set; }
        public virtual ImageGallery ImageGallery1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoxerWorkoutSchedule> BoxerWorkoutSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoxerWorkoutTemplateMapping> BoxerWorkoutTemplateMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoxerWorkoutUserMapping> BoxerWorkoutUserMappings { get; set; }
    }
}
