
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class BoxerWorkoutUserMapping
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public int BoxerWorkoutId { get; set; }

    public Nullable<int> LocationId { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime UpdatedDate { get; set; }

    public int UpdatedBy { get; set; }

    public bool IsActive { get; set; }



    public virtual BoxerWorkoutMaster BoxerWorkoutMaster { get; set; }

    public virtual Location Location { get; set; }

    public virtual User User { get; set; }

}

}
