//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxerTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoxerTemplate()
        {
            this.BoxerTemplateVideoMappings = new HashSet<BoxerTemplateVideoMapping>();
            this.BoxerWorkoutTemplateMappings = new HashSet<BoxerWorkoutTemplateMapping>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string TemplateDescription { get; set; }
        public Nullable<bool> IsReadyForLocations { get; set; }
        public string TemplateName { get; set; }
        public int NumberOfBasicVideos { get; set; }
        public int NumberOfAlterVideos { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string PrimaryText { get; set; }
        public string AlternateText { get; set; }
        public string PrimaryColor { get; set; }
        public string AlternateColor { get; set; }
        public string PrimaryGradientColor { get; set; }
        public string AlternateGradientColor { get; set; }
        public string PrimaryBackgroundColor { get; set; }
        public string AlternateBackgroundColor { get; set; }
        public string TimeText { get; set; }
        public string BlockLineOneText { get; set; }
        public string BlockLineTwoText { get; set; }
        public string GoalText { get; set; }
        public Nullable<bool> IsFooterText { get; set; }
        public string FooterTextColor { get; set; }
        public string FooterText { get; set; }
    
        public virtual BoxerTemplate BoxerTemplate1 { get; set; }
        public virtual BoxerTemplate BoxerTemplate2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoxerTemplateVideoMapping> BoxerTemplateVideoMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoxerWorkoutTemplateMapping> BoxerWorkoutTemplateMappings { get; set; }
    }
}
