
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class GymUserMapping
{

    public int Id { get; set; }

    public Nullable<int> GymId { get; set; }

    public Nullable<int> UserId { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual Gym Gym { get; set; }

    public virtual User User { get; set; }

}

}
