
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Location
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Location()
    {

        this.BoxerWorkoutUserMappings = new HashSet<BoxerWorkoutUserMapping>();

        this.GymLocationMappings = new HashSet<GymLocationMapping>();

        this.UserLocationMappings = new HashSet<UserLocationMapping>();

        this.WorkoutSchedules = new HashSet<WorkoutSchedule>();

        this.WorkoutSchedules1 = new HashSet<WorkoutSchedule>();

        this.WorkoutUserMappings = new HashSet<WorkoutUserMapping>();

    }


    public int ID { get; set; }

    public string LocationName { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string Phone { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public Nullable<int> CityId { get; set; }

    public string ZipCode { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BoxerWorkoutUserMapping> BoxerWorkoutUserMappings { get; set; }

    public virtual City City { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GymLocationMapping> GymLocationMappings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserLocationMapping> UserLocationMappings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WorkoutSchedule> WorkoutSchedules { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WorkoutSchedule> WorkoutSchedules1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WorkoutUserMapping> WorkoutUserMappings { get; set; }

}

}
