
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class TrainingPortalSubCategory
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TrainingPortalSubCategory()
    {

        this.TrainingPortalSubCategoryVideos = new HashSet<TrainingPortalSubCategoryVideo>();

    }


    public long Id { get; set; }

    public long TrainingPortalId { get; set; }

    public long TrainingPortalCategoryId { get; set; }

    public string Name { get; set; }

    public int DisplayOrder { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int UpdatedBy { get; set; }

    public System.DateTime UpdatedDate { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }



    public virtual TrainingPortal TrainingPortal { get; set; }

    public virtual TrainingPortalCategory TrainingPortalCategory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingPortalSubCategoryVideo> TrainingPortalSubCategoryVideos { get; set; }

}

}
