
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class TrainingPortal
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TrainingPortal()
    {

        this.TrainingPortalCategories = new HashSet<TrainingPortalCategory>();

        this.TrainingPortalSubCategories = new HashSet<TrainingPortalSubCategory>();

        this.TrainingPortalUserMappings = new HashSet<TrainingPortalUserMapping>();

    }


    public long Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int UpdatedBy { get; set; }

    public System.DateTime UpdatedDate { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingPortalCategory> TrainingPortalCategories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingPortalSubCategory> TrainingPortalSubCategories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingPortalUserMapping> TrainingPortalUserMappings { get; set; }

}

}
