
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Video
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Video()
    {

        this.BoxerTemplateVideoMappings = new HashSet<BoxerTemplateVideoMapping>();

        this.TemplateVideoMappings = new HashSet<TemplateVideoMapping>();

        this.VideoTagMappings = new HashSet<VideoTagMapping>();

    }


    public int ID { get; set; }

    public string VideoTitle { get; set; }

    public string VideoAttachment { get; set; }

    public string ContentType { get; set; }

    public string SmallDescription { get; set; }

    public string FullDescription { get; set; }

    public Nullable<int> CounterOfUseInWorkout { get; set; }

    public Nullable<int> RepsCount { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public Nullable<int> DisplayOrder { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BoxerTemplateVideoMapping> BoxerTemplateVideoMappings { get; set; }

    public virtual Category Category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TemplateVideoMapping> TemplateVideoMappings { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VideoTagMapping> VideoTagMappings { get; set; }

}

}
