
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class WorkoutTemplateMapping
{

    public int ID { get; set; }

    public int WorkoutMasterID { get; set; }

    public int TemplateID { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public int DisplayOrder { get; set; }



    public virtual Template Template { get; set; }

    public virtual WorkoutMaster WorkoutMaster { get; set; }

}

}
